site_name:  C90_doc
site_url: https://doc.adamzhou.site/
site_author: AdamZh0u
site_description: >-
  Less is more.

repo_name: C90_doc
repo_url: https://github.com/AdamZh0u/C90_doc

docs_dir: doc

nav:
  - Home: 'index.md'
  - Python:
    - Pandas: 'python/pandas.md'
    - Matplotlib: 'python/mpl.md'
    - My plots: 'python/my_plots.md'
  - About: about.md

theme:
  name: material
  language: zh

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: false

  features:
    - header.autohide # 隐藏标题
    - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

plugins:
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true
extra:
  analytics:
    provider: google
    property: G-JGHVBFWGTV